스마트여성병원서비스/accounts/urls.py
from django.urls import path
from .views import signup_view,login_view, logout_view,signup_docotr_view

app_name='accounts'
urlpatterns=[
    path('signup/',signup_view, name='signup'),
    path('signup-doctor/',signup_docotr_view, name='signupdoctor'),
    
    path('login/',login_view, name='login'),
    path('logout/',logout_view, name='logout'),
    
]

스마트여성병원서비스/hospitalapp/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('',index, name='index'),
    path('hospital-detail/<int:hospital_id>',hospital_detail,name='hospital-detail'),
    path('hospital-detail/reservation/<int:hospital_id>',reservation, name='reservation'),
]

스마트여성병원서비스/스마트여성병원서비스/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from qnas.views import question_view, detail, question_create
from qnas import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hospitalapp.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('mypage/<str:username>/', question_view, name='mypage'),
    path('question/<int:question_id>/', views.detail, name='question-detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question_write/', views.question_create, name='question_write'),
    path('hospital/review/create/<str:user>/', views.review_create, name='review-create-url'),
    path('hospital/<str:hospital_name>/review/<int:review_id>/',views.mypage5, name='mypage5')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

스마트여성병원서비스/hospitalapp/models.py
from django.db import models

# Create your models here.
from users.models import User
# Create your models here.

class Hospital(models.Model): 
    CATEGORY=[
        ('서울특별시','서울특별시'),
        ('경기도','경기도'),
        ('인천광역시','인천광역시'),
        ('강원특별자치도','강원특별자치도'),
        ('대전광역시','대전광역시'),
        ('세종특별자치도','세종특별자치도'),
        ('충청남도','충청남도'),
        ('충청북도','충청북도'),
        ('부산광역시','부산광역시'),
        ('울산광역시','울산광역시'),
        ('경상남도','경상남도'),
        ('경상북도','경상북도'),
        ('대구광역시','대구광역시'),
        ('광주광역시','광주광역시'),
        ('전라남도','전라남도'),
        ('전라북도','전라북도'),
        ('제주특별자치도','제주특별자치도'),
    ]
    woman=models.BooleanField(verbose_name="여자전문의",default=False)
    night_care=models.BooleanField(verbose_name="야간진료",default=False)
    saturday_treatment=models.BooleanField(verbose_name="토요일 진료",default=False)
    holiday_treatment=models.BooleanField(verbose_name="공휴일 진료",default=False)
    sunday_care=models.BooleanField(verbose_name="일요일 진료",default=False)
    latitude=models.FloatField(verbose_name="위도",default=0.0) #지도에 표시하기 위함 
    longtitude=models.FloatField(verbose_name="경도",default=0.0)
    name = models.CharField(verbose_name="병원 이름",max_length=30)  
    content=models.TextField(verbose_name="병원 소개 내용",null=True)
    adress=models.CharField(verbose_name="병원 주소",max_length=200)
    image=models.ImageField(verbose_name="병원 소개 이미지",upload_to='hospital/',default=None,null=True)
    waiting=models.IntegerField(verbose_name="대기자수",default=0)
    created_at=models.DateTimeField(auto_now=True)
    where = models.CharField(verbose_name="병원 주소", default='', max_length=10, choices=CATEGORY)
    reservated_users = models.ManyToManyField(User, related_name='reservated_users',verbose_name="이 병원에 예약한 사용자")
    def increase_waiter(self):
        self.waiting+=1

class Review(models.Model):
    point=models.IntegerField(verbose_name="평점",null=True)
    title=models.CharField(max_length=20, null=True,verbose_name="제목")
    comment=models.TextField(verbose_name="내용")
    writer=models.CharField(max_length=20,null=True,verbose_name="작성자")
    hospital=models.ForeignKey(Hospital, on_delete=models.CASCADE,verbose_name="리뷰 대상 병원")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="생성일자") 

스마트여성병원서비스/hospitalapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Hospital, Review
from django.contrib.auth.decorators import login_required
from django.db.models import Count,Avg
# Create your views here.

def index(request):
    hospitals = Hospital.objects.all().annotate(reviews_count=Count('review')).annotate(average_point=Avg('review__point'))
    where = request.GET.get('where')
    title = request.GET.get('title')
    grade = request.GET.get('grade')
    night_care = request.GET.get('night_care')
    saturday_treatment = request.GET.get('saturday_treatment')
    holiday_treatment = request.GET.get('holiday_treatment')
    sunday_care = request.GET.get('sunday_care')
    woman = request.GET.get('woman')
    all_care=request.GET.get('all_care')
    print(where)
    if all_care:
        hospitals = hospitals.filter(night_care=True,saturday_treatment=True,holiday_treatment=True,sunday_care=True,woman=True)
    
    #추가로 넣어야 함 
    where_list = ['서울특별시','경기도','인천광역시','강원특별자치도','대전광역시','세종특별자치도','충청남도','충청북도','부산광역시','울산광역시','경상남도','경상북도','대구광역시','광주광역시','전라남도','전라북도','제주특별자치도']
    default_grade = 0
    print(holiday_treatment)
    if night_care:
        hospitals = hospitals.filter(night_care=True)
    if saturday_treatment:
        hospitals = hospitals.filter(saturday_treatment=True)
    if holiday_treatment:
        hospitals = hospitals.filter(holiday_treatment=True)
    if sunday_care:
        hospitals = hospitals.filter(sunday_care=True)
    if woman:
        hospitals = hospitals.filter(woman=True)
    
    if grade in ['1', '2', '3', '4']:
        default_grade = int(grade)

    if where in where_list:
        hospitals = hospitals.filter(where=where)
    if title:
        hospitals = hospitals.filter(name__contains=title)
    if default_grade > 0:
        hospitals = hospitals.filter(average_point__gte=default_grade)

    return render(request, 'index.html', {'hospitals': hospitals, 'default_grade': default_grade})

def hospital_detail(request, hospital_id):
    hospital=get_object_or_404(Hospital, id=hospital_id)
    reviews = Review.objects.filter(hospital=hospital).all()
    return render(request, 'hospital/hospital_detail.html', {'hospital': hospital, 'reviews': reviews})



@login_required
def reservation(request,hospital_id):
    hospital= get_object_or_404(Hospital, id=hospital_id)
    reviews = Review.objects.filter(hospital=hospital).all()
    if request.method=="POST":
        hospital.increase_waiter()
        hospital.reservated_users.add(request.user)

        return render(request, 'hospital/hospital_detail.html', {'hospital': hospital, 'reviews': reviews,'errors':'','finish':'예약완료'})

스마트여성병원서비스/hospitalapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'mypage' request.user %}">마이페이지</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    {% endif %}
    
    <div id="lat" style="display:none">
        {% for hos in hospitals %}
            {{hos.latitude}},
        {% endfor %}
    </div>
    <div id="lng" style="display:none">
        {% for hos in hospitals %}
            {{hos.longtitude}},
        {% endfor %}
    </div>
    <div id="name" style="display:none">
        {% for hos in hospitals %}
            {{hos.name}},
        {% endfor %}
    </div>
    <div id="map" style="width:100%;height:500px;"></div>

    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e59f4d4ca82146ab6bd68fbde0d4ec9f"></script>
    <script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = { 
            center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
            level: 5 // 지도의 확대 레벨 
        }; 
    
    var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다
    
    var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";     
    var imageSize = new kakao.maps.Size(24, 35); 
    imageOption = {offset: new kakao.maps.Point(27, 69)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.
// 마커의 이미지정보를 가지고 있는 마커이미지를 생성합니다
var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imageOption)

    // HTML5의 geolocation으로 사용할 수 있는지 확인합니다 
    if (navigator.geolocation) {
        
        // GeoLocation을 이용해서 접속 위치를 얻어옵니다
        navigator.geolocation.getCurrentPosition(function(position) {
            
            var lat = position.coords.latitude, // 위도
                lon = position.coords.longitude; // 경도
            
            var locPosition = new kakao.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
                message = '<div style="padding:5px;">현재 위치</div>'; // 인포윈도우에 표시될 내용입니다
            
            // 마커와 인포윈도우를 표시합니다
            displayMarker(locPosition, message);
                
          });
        
    } else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
        
        var locPosition = new kakao.maps.LatLng(33.450701, 126.570667),    
            message = 'geolocation을 사용할수 없어요..'
            
        displayMarker(locPosition, message);
    }
    
    // 지도에 마커와 인포윈도우를 표시하는 함수입니다
    function displayMarker(locPosition, message) {
    
        // 마커를 생성합니다
        var marker = new kakao.maps.Marker({  
            map: map, 
            position: locPosition,
            image:markerImage
        }); 
        
        var iwContent = message, // 인포윈도우에 표시할 내용
            iwRemoveable = true;
    
        // 인포윈도우를 생성합니다
        var infowindow = new kakao.maps.InfoWindow({
            content : iwContent,
            removable : iwRemoveable
        });
        
        // 인포윈도우를 마커위에 표시합니다 
        infowindow.open(map, marker);
        
        // 지도 중심좌표를 접속위치로 변경합니다
        map.setCenter(locPosition);  
        var positions=[]
    }   

    
    var latitudes = document.getElementById('lat').innerHTML.trim().split(',');
    var longitudes = document.getElementById('lng').innerHTML.trim().split(',');
    var names = document.getElementById('name').innerHTML.trim().split(',');

    // 마커 생성 및 지도에 표시
    for (var i = 0; i < latitudes.length; i++) {
        var marker = new kakao.maps.Marker({
            map: map,
            position: new kakao.maps.LatLng(parseFloat(latitudes[i]), parseFloat(longitudes[i])),
            title: names[i]
        });

        var infowindow = new kakao.maps.InfoWindow({
            content: '<div style="padding:5px;">' + names[i] + '</div>'
        });

        kakao.maps.event.addListener(marker, 'mouseover', makeListener(infowindow, marker));
        kakao.maps.event.addListener(marker, 'mouseout', makeunListener(infowindow, marker));
        
    }

    // 인포윈도우 클릭 이벤트 리스너 생성
    function makeListener(infowindow, marker) {
        return function() {
            infowindow.open(map, marker);
        };
    }
    function makeunListener(infowindow, marker) {
        return function() {
            infowindow.close(map, marker);
        };
    }
    </script>

    <form method="get" action="{% url 'index' %}">
        위치<select name="where">
            <option value="0">전체</option>
            <option value="서울특별시">서울</option>
            <option value="부산">부산</option>
            <option value="대구">대구</option>
            <option value="경기도">경기</option>
            
        </select>
        이름<input type="text" name="title">
        병원평점<select name="grade">
            <option value="0">선택안함</option>
            <option value="1">1점이상</option>
            <option value="2">2점이상</option>
            <option value="3">3점이상</option>
            <option value="4">4점이상</option>
        </select>
        여성전문의 진료<input name="woman" value="1" type="checkbox">
        전체<input value="1" name="all_care" type="checkbox">
        야간진료<input name="night_care" value="1" type="checkbox">
        토요일 진료<input name="saturday_treatment" value="1" type="checkbox">
        공휴일 진료<input name="holiday_treatment" value="1" type="checkbox">
        일요일 진료<input name="sunday_care" value="1" type="checkbox">
        
        <button type="submit">검색</button>
    </form>
    <a href="{% url 'index' %}"><button>초기화</button></a><br>
    {% for hospital in hospitals %}
        <a href="{% url 'hospital-detail' hospital.id %}"><h3>{{ hospital.name }}</h3></a>
        리뷰 : {{ hospital.reviews_count }}개, 평점 : 
        {% if hospital.average_point is None %}
            0
        {% else %}
            {{ hospital.average_point|floatformat:2 }}
        {% endif %}<br>
        {{ hospital.adress }}
    {% empty %}
        없음
    {% endfor %}
    

</body>
</html>